In [1]:
import pandas as pd
import numpy as np

In [6]:
data=pd.read_csv('train.csv')

In [7]:
data.head()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1

In [19]:
X=data.iloc[:, :-1]
Y=data.iloc[:,-1]

In [9]:
X=pd.DataFrame(X)
Y=pd.DataFrame(Y)

In [10]:
def normilize(X):
    u=X.mean(axis=0)
    std=X.std(axis=0)
    return (X-u)/std

In [11]:
normilize(X)

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
0,-0.902372,-0.989802,0.830572,-1.018929,-0.762304,-1.043705,-1.380298,0.340654,1.348911,-1.101696,-1.305424,-1.408596,-1.146497,0.391605,-0.784787,0.283032,1.462128,-1.786414,-1.005767,0.985850
1,-0.495015,1.009798,-1.252751,0.980932,-0.992642,0.957646,1.154735,0.687376,-0.120029,-0.664602,-0.645827,0.585631,1.704039,0.467200,1.113987,-0.635158,-0.734084,0.559501,0.993769,-1.013846
2,-1.537302,1.009798,-1.252751,0.980932,-0.531966,0.957646,0.493422,1.380820,0.134210,0.209587,-0.645827,1.392336,1.074699,0.441387,-0.310094,-0.864705,-0.368048,0.559501,0.993769,-1.013846
3,-1.418964,1.009798,1.198217,-1.018929,-0.992642,-1.043705,-1.214970,1.034098,-0.261274,0.646681,-0.151130,1.286428,1.236662,0.594421,0.876640,0.512579,-0.002013,0.559501,-1.005767,-1.013846
4,1.325574,1.009798,-0.394912,-1.018929,2.001753,0.957646,0.658751,0.340654,0.021215,-1.101696,0.673365,1.268401,-0.091429,-0.657502,-1.022134,-0.864705,0.730057,0.559501,0.993769,-1.013846
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,-1.011607,1.009798,-1.252751,0.980932,-0.992642,0.957646,-1.655845,1.034098,-0.967495,0.646681,0.673365,1.299948,1.477291,-1.342463,0.164600,-0.405610,1.462128,0.559501,0.993769,-1.013846
1996,1.653280,1.009798,1.320765,0.980932,-0.992642,-1.043705,0.383203,-1.046233,1.320663,-0.227507,-1.140525,0.608165,1.650822,-0.085010,-0.310094,0.971674,0.913075,0.559501,0.993769,0.985850
1997,1.530391,-0.989802,-0.762557,0.980932,-0.762304,0.957646,0.217875,0.687376,-0.910998,1.520869,-1.140525,0.502257,0.880345,0.859924,-0.784787,-1.094253,-1.100119,0.559501,0.993769,-1.013846
1998,0.622372,-0.989802,-0.762557,-1.018929,-0.071290,0.957646,0.768969,-1.392955,0.134210,0.209587,-0.810726,-0.696533,-1.345480,-1.157164,1.351334,0.971674,1.462128,0.559501,0.993769,0.985850
1999,-1.657916,1.009798,0.585475,0.980932,0.159048,0.957646,0.713860,1.380820,0.783934,0.646681,1.003164,-0.365288,-1.151125,1.654590,1.588680,-0.405610,-1.649172,0.559501,0.993769,0.985850

In [14]:
from sklearn.feature_selection import SelectKBest

In [15]:
best_features=SelectKBest()

In [21]:
fit=best_features.fit(X,Y)
fit.scores_

array([3.15981575e+01, 4.76767709e-01, 4.93707801e-01, 4.28239286e-01,
       7.72181960e-01, 1.05952453e+00, 2.92299608e+00, 1.50068244e+00,
       3.59431819e+00, 2.62541515e+00, 8.25446358e-01, 1.94848418e+01,
       2.26208825e+01, 3.52011082e+03, 2.22598374e+00, 1.67099983e+00,
       1.62881131e+00, 4.57319750e-01, 1.29330223e+00, 2.84940470e-01])

In [20]:
print(X.shape)
print(Y.shape)

(2000, 20)
(2000,)

In [28]:
dfscores=pd.DataFrame(fit.scores_)
dfcolumns= pd.DataFrame(X.columns)

In [29]:
featureScores = pd.concat([dfcolumns, dfscores], axis = 1)
featureScores.columns = ['Features', 'Scores']